server:
  port: 8080

spring:
  session:
    store-type: redis
  redis:
    host: bank-redis
    port: 6379
  security:
    oauth2:
      client:
        registration:
          keycloak:
            provider: keycloak-provider
            client-id: web-client
            client-secret: wzpcA6bISWDI3oTn6eJaXS2eIXIj6wKw 
            authorization-grant-type: authorization_code
            scope:
              - openid
              - profile
              - email
            redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"
        provider:
          keycloak-provider:
           
            authorization-uri: http://localhost:8084/realms/bank-realm/protocol/openid-connect/auth
            
            token-uri: http://bank-keycloak:8080/realms/bank-realm/protocol/openid-connect/token
            
            issuer-uri: http://localhost:8084/realms/bank-realm
           
            jwk-set-uri: http://bank-keycloak:8080/realms/bank-realm/protocol/openid-connect/certs
           
            user-info-uri: http://bank-keycloak:8080/realms/bank-realm/protocol/openid-connect/userinfo  cloud:
    gateway:
      routes:
        - id: deposit-service
          uri: lb://DEPOSIT-SERVICE
          predicates:
            - Path=/api/deposits/**, /api/accounts/**, /api/deposit-types/**
          filters:
            - TokenRelay 
