server:
  port: 8080

spring:
  session:
    store-type: redis
  redis:
    host: bank-redis
    port: 6379
  security:
    oauth2:
      client:
        registration:
          keycloak:
            provider: keycloak-provider
            client-id: web-client
            client-secret: SUtRkmXr67PwNi2f4PlnMhQjjDx7TmZC
            authorization-grant-type: authorization_code
            scope: 
              - openid
              - profile
              - email
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        provider:
          keycloak-provider:
            issuer-uri: http://bank-keycloak:8080/realms/bank-realm
  cloud:
    gateway:
      httpclient:
        connect-timeout: 10000
        response-timeout: 10s
      routes:
        - id: deposit-service
          uri: lb://DEPOSIT-SERVICE
          predicates:
            - Path=/api/deposits/**, /api/accounts/**, /api/deposit-types/**
          filters:
            - TokenRelay
