spring:
  session:
    store-type: redis
    timeout: 30m

  data:
    redis:
      host: redis
      port: 6379

  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://keycloak.bank.local:8080/realms/bank-realm
            jwk-set-uri: http://bank-keycloak:8080/realms/bank-realm/protocol/openid-connect/certs
            token-uri: http://bank-keycloak:8080/realms/bank-realm/protocol/openid-connect/token
            user-info-uri: http://bank-keycloak:8080/realms/bank-realm/protocol/openid-connect/userinfo
            
            authorization-uri: http://keycloak.bank.local:8084/realms/bank-realm/protocol/openid-connect/auth
        registration:
          gateway:
            provider: keycloak
            client-id: web-client
            client-secret: wzpcA6bISWDI3oTn6eJaXS2eIXIj6wKw
            scope:
              - openid
              - profile
              - email

  cloud:
    gateway:
      default-filters:
        - SaveSession
      routes:
        - id: deposit-service
          uri: lb://DEPOSIT-SERVICE
          predicates:
            - Path=/api/deposits/** , /api/deposit-types/**, /api/accounts/**

eureka:
  client:
    service-url:
      defaultZone: http://bank-eureka-server:8761/eureka
