spring:
  application:
    name: bank-gateway

  profiles:
    active: docker

  config:
    import: optional:configserver:http://bank-config-server:8888

  session:
    store-type: redis
    timeout: 30m

  data:
    redis:
      host: bank-redis
      port: 6379

  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://keycloak.bank.local:8084/realms/bank-realm
        registration:
          gateway:
            provider: keycloak
            client-id: bank-gateway
            client-secret: ${KEYCLOAK_CLIENT_SECRET}
            scope:
              - openid
              - profile
              - email

  cloud:
    gateway:
      default-filters:
        - SaveSession
      routes:
        - id: account-service
          uri: lb://ACCOUNT-SERVICE
          predicates:
            - Path=/accounts/**

eureka:
  client:
    service-url:
      defaultZone: http://bank-eureka-server:8761/eureka
