server:
  port: 8081
  servlet:
    context-path: /auth

spring:
  application:
    name: auth-service
  
  datasource:
    url: jdbc:postgresql://localhost:5432/auth_service
    username: admin
    password: admin
    
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth-service:8081/auth
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  secret: testpassword
  expiration: 86400000  # 24 hours
  refresh-token-expiration: 2592000000  # 30 days

# security:
#   oauth2:
#     client:
#       registration:
#         web-client:
#           client-id: web-client
#           client-secret: secret
#           authorization-grant-type: password
#           scope: read,write
#           access-token-validity-seconds: 3600
#           refresh-token-validity-seconds: 2592000
#         mobile-client:
#           client-id: mobile-client
#           client-secret: mobillesecret
#           authorization-grant-type: password
#           scope: read

password:
  policy:
    min-length: 8
    require-uppercase: true
    require-lowercase: true
    require-digits: true
    require-special-chars: true
