server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://auth-db:5432/auth_db
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      authorizationserver:
        issuer: http://auth-service:8081 
