server:
  port: 8081
  servlet:
    context-path: /auth

spring:
  application:
    name: auth-service
  
  datasource:
    url: jdbc:postgresql://localhost:5432/auth_service
    username: admin
    password: admin
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  # ПРАВИЛЬНАЯ конфигурация Authorization Server
  security:
    oauth2:
      authorization-server:
        client:
          web-client:
            client-id: web-client
            client-secret: secret
            authorization-grant-types: 
              - client_credentials
              - authorization_code
              - refresh_token
            scopes: 
              - openid
              - profile
              - read
              - write
            redirect-uris: 
              - http://localhost:8080/login/oauth2/code/web-client
            require-authorization-consent: false
            client-authentication-methods:  # ← ДОБАВЬТЕ ЭТУ СЕКЦИЮ!
              - client_secret_basic

logging:
  level:
    org.springframework.security: DEBUG
    org.work.authservice: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
      show-components: always

password:
  policy:
    min-length: 8
    require-uppercase: true
    require-lowercase: true
    require-digits: true
    require-special-chars: true
