server:
  port: 8081
  servlet:
    context-path: /auth

spring:
  application:
    name: auth-service
  
  datasource:
    url: jdbc:postgresql://localhost:5432/auth_service
    username: admin
    password: admin
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

# УДАЛИТЕ ВСЮ СЕКЦИЮ spring.security.oauth2.authorization-server

logging:
  level:
    org.springframework.security: DEBUG
    org.work.authservice: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
      show-components: always

password:
  policy:
    min-length: 8
    require-uppercase: true
    require-lowercase: true
    require-digits: true
    require-special-chars: true
