server:
  port: 8081

spring:
  application:
    name: auth-service
  
  datasource:
    url: jdbc:postgresql://localhost:5432/auth_service
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driverserver:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://auth-db:5432/auth_db
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      authorizationserver:
        issuer: http://auth-service:8081 
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        default_schema: public
    open-in-view: false

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
    initial-instance-info-replication-interval-seconds: 5
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10

logging:
  level:
    org.springframework.security: DEBUG
    org.work.authservice: DEBUG
    org.springframework.security.oauth2: DEBUG
    org.hibernate.SQL: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
      show-components: always

password:
  policy:
    min-length: 8
    require-uppercase: true
    require-lowercase: true
    require-digits: true
    require-special-chars: true
