# config-repo/deposit-service.yml
# СПЕЦИФИЧНЫЕ НАСТРОЙКИ ДЛЯ DEPOSIT SERVICE

server:
  port: 8082
  servlet:
    context-path: /api

spring:
  application:
    name: deposit-service
  
  # OAuth2 Resource Server
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/auth

# Business Configuration
deposit:
  settings:
    max-amount: 1000000
    min-amount: 1000
    max-active-deposits: 5
    auto-renewal-enabled: true
  
  # Deposit Types
  types:
    savings:
      name: "Накопительный"
      min-amount: 1000
      max-amount: 1000000
      interest-rate: 5.5
      duration-days: 365
      early-withdrawal-penalty: 1.0
      capitalization: true
    
    fixed-term:
      name: "Срочный"
      min-amount: 50000
      max-amount: 500000
      interest-rate: 7.0
      duration-days: 730
      early-withdrawal-penalty: 2.0
      capitalization: false
    
    demand:
      name: "До востребования"
      min-amount: 100
      max-amount: 10000000
      interest-rate: 1.5
      duration-days: 0
      early-withdrawal-penalty: 0.0
      capitalization: false

# Interest Calculation
interest:
  calculation-time: "00:00"
  tax-rate: 13.0
  rounding-scale: 2