server:
  port: 8082
  servlet:
    context-path: /api

spring:
  application:
    name: deposit-service

  datasource:
    url: jdbc:postgresql://postgres-deposit:5432/deposit_service
    username: deposit
    password: deposit
    
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://auth-service:8081/auth
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/.well-known/jwks.json
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        show_sql: true

app:
  deposit:
    settings:
      max-amount: 1000000
      min-amount: 1000
      max-active-deposits: 5
      auto-renewal-enabled: true
    
    interest:
      calculation-time: "00:00"
      tax-rate: 13.0
      rounding-scale: 2
      days-in-year: 365

logging:
  level:
    org.work.depositservice: DEBUG
    org.springframework.security: INFO
    org.hibernate.SQL: DEBUG
