server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://deposit_db:5433/deposit_db
    username: deposit_user
    password: password
  spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/bank-realm
eureka:
  client:
    service-url:
      defaultZone: http://bank-eureka-server:8761/eureka
