server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://deposit-db:5432/deposit_db
    username: user
    password: password
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://AUTH-SERVICE/auth
