server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://deposit-db:5432/deposit_db
    username: deposit_user
    password: password
  spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak.bank.local:8084/realms/bank-realm

