server:
  port: 8083

spring:
  application:
    name: transaction-service

  datasource:
    url: jdbc:postgresql://postgres-transaction:5432/transaction_service
    username: transaction
    password: transaction

redis:
  host: localhost
  port: 6379
  password: ""
  db: 0
  pool-size: 10
  min-idle-conns: 2

services:
  auth:
    url: http://localhost:8081/auth
    timeout: 5000
  deposit:
    url: http://localhost:8082/api
    timeout: 5000
  eureka:
    url: http://localhost:8761/eureka/
    enabled: true

transaction:
  max-retries: 3
  timeout-seconds: 30
  batch-size: 100
  max-concurrent: 10

interest:
  calculation-time: "00:00"
  tax-rate: 13.0
  batch-size: 50

notification:
  email-enabled: true
  sms-enabled: false
  email-from: masterov_k@bk.ru
  sms-provider-url: ""
  retry-attempts: 3
  retry-delay: 5000

log:
  level: "info"
  file: "logs/transaction-service.log"
  max-size: 100
  max-backups: 7
  max-age: 30
