server:
  port: 8080
  servlet:
    context-path: /

spring:
  application:
    name: web-service
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
  web:
    resources:
      static-locations: classpath:/static/

# Конфигурация сервисов
services:
  auth:
    url: http://auth-service:8081
    timeout: 10000
  # deposit:
  #   url: http://deposit-service:8082/api
  #   timeout: 10000
  # transaction:
  #   url: http://transaction-service:8083
  #   timeout: 10000

# Логирование
logging:
  level:
    org.example.webservice: DEBUG
    org.springframework.web: INFO
    org.springframework.security: INFO

# Actuator для здоровья приложения
management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always
