# config-repo/web-service.yml
server:
  port: 8080

spring:
  thymeleaf:
    cache: true
  resources:
    chain:
      cache: true
      compressed: true

services:
  auth:
    url: http://auth-service:8081/auth
    timeout: 10000
  # deposit:
  #   url: http://deposit-service:8082/api
  #   timeout: 10000
  # transaction:
  #   url: http://transaction-service:8083
  #   timeout: 10000

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

logging:
  level:
    org.bank.ui: INFO
