# config-repo/web-service.yml

server:
  port: 8080 # Локальный порт для Web-Service
  servlet:
    context-path: /

spring:
  application:
    name: web-service
    
  # =================================================================
  # 1. SPRING SECURITY: OAUTH2 CLIENT CONFIGURATION (ОСНОВНОЕ)
  # =================================================================
  security:
    oauth2:
      client:
        registration:
          web-client:
            client-id: web-client
            client-secret: secret
            client-authentication-method: client_secret_basic
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: openid, profile
        provider:
          web-client:
            authorization-uri: http://localhost:8081/auth/oauth2/authorize
            token-uri: http://localhost:8081/auth/oauth2/token
            user-info-uri: http://localhost:8081/auth/userinfo
            user-name-attribute: sub
            jwk-set-uri: http://localhost:8081/auth/oauth2/jwks
          bank-auth-server:
            # URI эмитента — публичный адрес Auth Server'а (localhost для локальной проверки)
            issuer-uri: http://localhost:8081/auth 

  # =================================================================
  # 2. WEB, THYMELEAF & RESOURCES
  # =================================================================
  thymeleaf:
    cache: false # Отключаем кэш Thymeleaf для упрощения локальной разработки
    prefix: classpath:/templates/
  web:
    resources:
      static-locations: classpath:/static/

# =================================================================
# 3. API SERVICE URLs
# =================================================================
# Эти URL используются в классе ApiService для прямых вызовов API 
# (например, для регистрации, которая не идет через OAuth2).
api:
  # URL для Auth Service (для регистрации/прямых API вызовов)
  auth-service-url: http://localhost:8081/auth 
  
  # URL для Resource Server'ов (если Web Service будет вызывать их напрямую)
  deposit-service-url: http://localhost:8082/api
  transaction-service-url: http://localhost:8083/api
  
  # Установка таймаута для RestTemplate (для всех сервисов)
  timeout: 10000

# =================================================================
# 4. EUREKA CLIENT
# =================================================================
eureka:
  client:
    # Eureka Client получит defaultZone из общего application.yml, 
    # но можно переопределить здесь, если требуется:
    # service-url:
    #   defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: false # В локальной среде лучше использовать hostname
    # lease-renewal-interval-in-seconds: 5 # Получено из общего application.yml

# =================================================================
# 5. LOGGING
# =================================================================
logging:
  level:
    # Увеличиваем уровень логирования для Security, чтобы видеть, что происходит с токенами
    org.springframework.security: DEBUG
    org.example.webservice: DEBUG
    org.springframework.web: INFO
    
# =================================================================
# 6. ACTUATOR
# =================================================================
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
      show-components: always
